spring:
  #数据库连接配置
  datasource:
    username: root
    password: lucong
    url: jdbc:mysql://172.17.162.83:3306/aqi_china?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    #端口号
    port: 5672
    #用户名
    password: guest
    #密码
    username: guest
    #主机
    host: 172.17.162.83
    #虚拟主机(一个RabbitMQ服务可以配置多个虚拟主机，每一个虚拟机主机之间是相互隔离，相互独立的，授权用户到指定的virtual-host就可以发送消息到指定队列)
    virtual-host: /
    #消息发送确认回调
    publisher-confirm-type: correlated
    # 路由失败回调
    publisher-returns: true
    template:
      # 必须设置成true 消息路由失败通知监听者，而不是将消息丢弃
      mandatory: true
    Listener:
      simple:
        # 每次从RabbitMQ获取的消息数量
        prefetch: 3
        default-requeue-rejected: false
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 5
        # 手动签收ACK
        acknowledge-mode: manual
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 172.17.162.83
    #host: 39.105.231.100
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: app_talk@123
    lettuce:
      pool:
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        shutdown-timeout: 2000ms
      timeout: 5000ms
redisson:
  address: redis://172.17.162.83:6379
  password: app_talk@123

ip:
  path: /data/my.datx