server:
  port: 9090
spring:
  #数据库连接配置
  datasource:
    username: root
    password: lucong
    url: jdbc:mysql://39.105.231.100:3306/aqi_china?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver